project:
  type: website
  output-dir: docs
  
website:
  title: "ARSRL DigiEpi Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Module
        menu:
          - module1/module1.qmd
          - module2/module2.qmd
          - module3/module3.qmd
          - module4/module4.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: united
    toc: true

editor: source

