project:
  type: website
  output-dir: docs
  
website:
  title: "ARSRL DigiEpi Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: syllabus.qmd
        text: Syllabus  
      - href: speakers.qmd
        text: Resource Speakers
      - href: concept_overview.qmd
        text: Concept Overview
      - text: Module
        menu:
          - module1/module1.qmd
          - module2/module2.qmd
          - module3/module3.qmd
          - module4/module4.qmd
          - module5/module5.qmd
      - text: Workshop Materials
        menu:
          - href: https://microreact.org/project/kpn-digiepi-fhi360
            text: Microreact Project
          - microreact_activity.qmd
          - pre_test/pre_test.qmd
          - post_test/post_test.qmd
          - quick_guide.qmd
      - href: https://9lzm79dg.forms.app/got-a-question-form
        text: Got a question?
          
    tools:
      - icon: link
        href: https://www.arsp.com.ph
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Antimicrobial Resistance Surveillance Reference Laboratory"

format:
  html:
    theme: united
    page-layout: full
    toc: true

editor: source

